version: '3.4'
services:
  solar-energy-api:
    build: 
      context: .
      dockerfile: SolarEnergyApi.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "7140:80"
    depends_on:
      - mssql-server
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "solarEnergy123"
    ports:
      - "1433:1433"
    volumes:
      - C:\dados\volumes\sqlserver:/var/opt/mssql/data
    expose:
      - 1433